// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jaceovdegjinjenhqgrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphY2VvdmRlZ2ppbmplbmhxZ3JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzNTUxNjksImV4cCI6MjA4ODkzMTE2OX0.d_W0RlqAQhbe8FjmeMHle85yHxdEvV33XuPlHaYExHM";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);